services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - DATABASE_URL=/app/data/sqlite.db
      - BETTER_AUTH_SECRET=fdfb455b88da6c3ee1c676d4999ab21711ff63be244db8f5999335ef98da4311
      - BETTER_AUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - db-data-dev:/app/data
    command: sh -c "npm run db:push && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped

volumes:
  db-data-dev:
