FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development
ENV PORT=3000
ENV DATABASE_URL=/app/data/sqlite.db
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
