services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=/app/data/sqlite.db
      - BETTER_AUTH_SECRET=fdfb455b88da6c3ee1c676d4999ab21711ff63be244db8f5999335ef98da4311
      - BETTER_AUTH_URL=http://localhost:3000
    volumes:
      - db-data:/app/data
    restart: unless-stopped

volumes:
  db-data:
